project_name: vc

release:
  prerelease: auto
  draft: true # we only publish after the Windows MSI gets uploaded
  name_template: "VulnCheck CLI {{.Version}}"

before:
  hooks:
    - >-
      {{ if eq .Runtime.Goos "windows" }}echo{{ end }} make manpages VC_VERSION={{.Version}}
    - >-
      {{ if ne .Runtime.Goos "linux" }}echo{{ end }} make completions

builds:
  - id: macos #build:macos
    goos: [darwin]
    goarch: [amd64, arm64]
    hooks:
      post:
        - cmd: ./script/sign '{{ .Path }}'
          output: true
    binary: bin/vc
    main: ./cmd/vc
    ldflags:
      - -s -w -X github.com/vulncheck-oss/cli/internal/build.Version={{.Version}} -X github.com/vulncheck-oss/cli/internal/build.Date={{time "2006-01-02"}}

  - id: linux #build:linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: bin/vc
    main: ./cmd/vc
    ldflags:
      - -s -w -X github.com/vulncheck-oss/cli/internal/build.Version={{.Version}} -X github.com/vulncheck-oss/cli/internal/build.Date={{time "2006-01-02"}}

  - id: windows #build:windows
    goos: [windows]
    goarch: [386, amd64, arm64]
    hooks:
      post:
        - cmd: >-
            {{ if eq .Runtime.Goos "windows" }}pwsh .\script\sign.ps1{{ else }}./script/sign{{ end }} '{{ .Path }}'
          output: true
    binary: bin/vc
    main: ./cmd/vc
    ldflags:
      - -s -w -X github.com/vulncheck-oss/cli/internal/build.Version={{.Version}} -X github.com/vulncheck-oss/cli/internal/build.Date={{time "2006-01-02"}}

archives:
  - id: linux-archive
    builds: [linux]
    name_template: "vc_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
      - ./share/man/man1/vc*.1
  - id: macos-archive
    builds: [macos]
    name_template: "vc_{{ .Version }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: zip
    files:
      - LICENSE
      - ./share/man/man1/vc*.1
  - id: windows-archive
    builds: [windows]
    name_template: "vc_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE

nfpms: #build:linux
  - license: MIT
    maintainer: GitHub
    homepage: https://github.com/vulncheck-oss/cli
    bindir: /usr
    dependencies:
      - git
    description: VulnCheck's official command line tool.
    formats:
      - deb
      - rpm
    contents:
      - src: "./share/man/man1/vc*.1"
        dst: "/usr/share/man/man1"
      - src: "./share/bash-completion/completions/vc"
        dst: "/usr/share/bash-completion/completions/vc"
      - src: "./share/fish/vendor_completions.d/vc.fish"
        dst: "/usr/share/fish/vendor_completions.d/vc.fish"
      - src: "./share/zsh/site-functions/_vc"
        dst: "/usr/share/zsh/site-functions/_vc"
